N = 100; PulseWidth = 10;
t = [0:1:(N-1)];
x = [ones(1,PulseWidth), zeros(1,N-PulseWidth)];
f = [-(N/2):1:(N/2)-1]*(1/N);
%wt = x.*(exp(1j*(pi/3).*t));
%wt = x.*(exp(-1j*(pi/3).*t));
wt = x.*cos((pi/3).*t);
Ww = fft(wt);
figure;
subplot(2,1,1);
plot(f,fftshift(abs(Ww)));
grid on;
xlabel('t');
ylabel('Magnitude');
title('Figure 8: w+(t) Magnitude Spectra');
subplot(2,1,2);
plot(f,fftshift(angle(Ww)));
grid on;
xlabel('t');
ylabel('Phase');
title('Figure 8: w+(t) Phase Spectra');