N = 100;
PulseWidth = 10;
x = [ones(1,PulseWidth), zeros(1,N-PulseWidth)];
z = conv(x,x);
Zf = fft(z);
f = [-(N-1):1:(N-1)].*1/(2*N - 1);
figure(2);
subplot(2, 1, 1);
plot(f, fftshift (abs (Zf)));
xlabel('f');
ylabel('Magnitude');
title('Figure 2: z(t) Magnitude Spectra');
grid on;
subplot(2, 1, 2);
plot(f, fftshift (angle(Zf)));
xlabel('f');
ylabel('Phase');
title('Figure 3: z(t) Phase Spectra');
grid on;
